version: 2.1
orbs:
  python: circleci/python@2.1.1
  
jobs:
  test_execution:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "Execute Python Script"
          command: python src/script.py
          
workflows:
  my-workflow:
    jobs:
      - test_execution
