version: 2.1
orbs:
  python: circleci/python@2.1.1
  
jobs:
  test_execution:
    executor: python/default
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: "Execute Python Script"
          command: |
          . venv/bin/activate
          python script.py
          
workflows:
  my-workflow:
    jobs:
      - test_execution
